### ISSUE TITLE
Node data cannot be read

### ISSUE THREAD

**Issue by daliansky** [benbaker76/PinConfigurator#1]
Hi,headkaze.
I tried to localize your new project and found that Nid could not read the data. I hope the next version will be fixed.

Thank you for your hard work.

**Comment by benbaker76** [comment]
What do you mean by "Nid could not read the data."?

**Comment by daliansky** [comment]
All Nid values ​​are all 0, not similar to 0x12, 0x13,...

**Comment by benbaker76** [comment]
If you're talking about importing from IORegistry then the Nid value is not available to import.

**Comment by daliansky** [comment]
> If you're talking about importing from IORegistry then the Nid value is not available to import.

I understanded, I am using IOREG imported directly.
