### ISSUE TITLE
add support new dumper - HdaCodecDump.efi

### ISSUE THREAD

**Issue by ctich** [benbaker76/PinConfigurator#3]
Hi, please add the ability to create a pin code using the new utility - HdaCodecDump.efi
https://github.com/acidanthera/OpenCorePkg/tree/master/Application/HdaCodecDump
Thanks!

Codec dump for example ALC887.
[RaeltekALC887.txt.zip](https://github.com/headkaze/PinConfigurator/files/4288621/RaeltekALC887.txt.zip)

**Comment by benbaker76** [comment]
Please try 2.2.3

EDIT: I didn't realize these dumps have multiple codecs. Need to do another update. Stay tuned.

**Comment by benbaker76** [comment]
I added a codec selection panel. Please try 2.2.4.

**Comment by ctich** [comment]
> I added a codec selection panel. Please try 2.2.4.
That's OK thanks!
