### ISSUE TITLE
v2.2.5, bug or not?

### ISSUE THREAD

**Issue by ctich** [benbaker76/PinConfigurator#4]
So it should be?
![Знімок екрана 2020-03-17 о 09 23 32](https://user-images.githubusercontent.com/42576487/76832110-5b241900-6831-11ea-92f1-b00cc7acd14e.png)

**Comment by benbaker76** [comment]
I'm not sure why it's listing your PCI bridge as an audio device. If you open IORegistry and enter IOAudioDevice into the search you will see what devices it enumerates.

Can you post your .ioreg file here?

**Comment by ctich** [comment]
> I'm not sure why it's listing your PCI bridge as an audio device. If you open IORegistry and enter IOAudioDevice into the search you will see what devices it enumerates.
> 
> Can you post your .ioreg file here?

[iMac_Sergey.zip](https://github.com/headkaze/PinConfigurator/files/4344847/iMac_Sergey.zip)

**Comment by benbaker76** [comment]
Can you please try 2.2.6

**Comment by ctich** [comment]
> Can you please try 2.2.6

now so:
![Знімок екрана 2020-03-17 о 22 39 52](https://user-images.githubusercontent.com/42576487/76899478-50549d00-68a0-11ea-9ec3-3e0c0102a049.png)

**Comment by benbaker76** [comment]
Can you please try this version [PinConfigurator_Test.zip](https://headsoft.com.au/download/mac/PinConfigurator_Test.zip)

If that doesn't work please try [PinConfigurator_Test2.zip](https://headsoft.com.au/download/mac/PinConfigurator_Test2.zip)

**Comment by ctich** [comment]
> Can you please try this version [PinConfigurator_Test.zip](https://headsoft.com.au/download/mac/PinConfigurator_Test.zip)
> 
> If that doesn't work please try [PinConfigurator_Test2.zip](https://headsoft.com.au/download/mac/PinConfigurator_Test2.zip)
**PinConfigurator_Test.zip** - all the same.

**PinConfigurator_Test2.zip** - now it's right:
![Знімок екрана 2020-03-18 о 18 43 34](https://user-images.githubusercontent.com/42576487/76985223-949b7800-6948-11ea-9535-4b5c9b6556a2.png)

**Comment by benbaker76** [comment]
I've released 2.2.7 hopefully nothing new is broken!

**Comment by ctich** [comment]
> I've released 2.2.7 hopefully nothing new is broken!
checked, everything is fine.
