### ISSUE TITLE
PinConfigs.kext not exporting

### ISSUE THREAD

**Issue by sanoj-m** [benbaker76/PinConfigurator#5]
I have imported and changed the properties of the pin profiles. When I click export-->PinConfigs.kext, its asking where to save, once I have selected the area to save, it does nothing.

**Comment by benbaker76** [comment]
You need to download [AppleALC](https://github.com/acidanthera/AppleALC) and when you select Export->PinConfigs.kext browse to the AppleALC/Resources folder where PinConfigs.kext is located and it should add the properties to the PinConfigs.kext//Contents/Info.plist file.

Note however this is not enough to create a working configuration for your audio device. You still need to create a Platforms.xml file. The feature to automatically create this using PinConfigurator was never implemented. You can read more about it [here](https://osxlatitude.com/forums/topic/1946-complete-applehda-patching-guide/)

**Comment by seaurching** [comment]
> Note however this is not enough to create a working configuration for your audio device. You still need to create a Platforms.xml file. The feature to automatically create this using PinConfigurator was never implemented. You can read more about it [here](https://osxlatitude.com/forums/topic/1946-complete-applehda-patching-guide/)

@benbaker76 when i export pinconfigs.kext, I compared the file found that file's md5 was same. That mean the codes have been add to kext?
