### ISSUE TITLE
Support for Monterey and Ventura

### ISSUE THREAD

**Issue by MiddlemanTM** [benbaker76/PinConfigurator#7]
Hi @headkaze 

So I tried Pin Configurator earlier today on my system running Monterey 12.4 and it failed to load the app.
Would it be possible to have it updated to macOS Monterey and Ventura?

**Comment by benbaker76** [comment]
If you run it from Terminal does it spit out an error?

**Comment by MiddlemanTM** [comment]
Yes it does. It says permission denied under Monterey.

It's odd because I've run it from Big Sur before without problems.

**Comment by benbaker76** [comment]
Can you post the output here please.

What happens when you run it via `sudo`?

**Comment by MiddlemanTM** [comment]
When I put it through sudo it came out with this:

Middleman@Mac ~ % sudo /Users/Middleman/Downloads/PinConfigurator.app 
Password:
sudo: /Users/Middleman/Downloads/PinConfigurator.app: command not found
Middleman@Mac ~ % 

Edit: I know what the problem is now - I was using v2.2.7 instead of 2.2.8. It's working now!
